{
 "title": "URL Shortener Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "URL Generation Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(url_shortener_generated_total[1m])",
     "legendFormat": "{{one_time}}"
    }
   ]
  },
  {
   "title": "URL Access Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(url_shortener_access_total[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Rate Limit Exceeded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(url_shortener_rate_limit_exceeded_total[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{route!=\"/metrics\"}[1m])",
     "legendFormat": "{{status_code}} {{method}} {{route}}"
    }
   ]
  }
 ]
}