version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener-app
    ports:
      - "3000:3000"
    volumes:
      # Mount the source code for live reloading
      - ./src:/app/src
      # Mount dist directory for TypeScript watch mode
      - ./dist:/app/dist
      # Don't mount node_modules from host to container
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=url-shortener
      - DB_PASSWORD=password
      - DB_NAME=url-shortener
    # Keep the container running
    tty: true
    restart: unless-stopped
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: url-shortener-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=url-shortener
      - MYSQL_USER=url-shortener
      - MYSQL_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql-data:
